### ISSUE TITLE
NS_ERROR_NOT_AVAILABLE

### ISSUE THREAD

**Issue by souperk** [ejci/favico.js#92]
Hello, I was trying to integrate https://github.com/jsxc/jsxc on my http://simplemachines.org forum (http://poke.lagos.p4u.gr) and I fell in this error. After some digging I traced the error on jsxc.dep.js on lines 32979 or favico.js on line 152 (since jsxc.dep.js is a copy of favico.js adding depedencies only).

```javascript
_context.drawImage(_img, 0, 0, _w, _h);
```

After that I changed the line and it seems to work.
```javascript
_img.onload = function(){_context.drawImage(_img, 0, 0, _w, _h);};
```
I note that I have tested with Firefox and Chromonium (same as Chrome) browser, and Chromonium seems to work fine without the fix, while Firefox doesn't.

Do you approve of this fix? Do you have anything else to recommend? 

If you approve I will fork the project and make a merge request. Also, I think it is better programming practise to use an EventListener instead.

**Comment by sualko** [comment]
Related jsxc/jsxc#208

**Comment by ejci** [comment]
Thanks for reporting and fixing it. I merged the pull request.

**Comment by anuragagarwal561994** [comment]
why was this commit reverted back? I am still facing the issue

**Comment by sualko** [comment]
@ejci Please provide some information, why this was reverted. Thanks.

**Comment by ejci** [comment]
@sualko I pushed a different fix for that issue. 
Sorry for not explaining why I reverted. The problem was that the original fix was in wrong place. The change should be in ``init`` method (see my commit). I tested it on FF and it looks fine. Pls let me know it works also for you.

**Comment by sualko** [comment]
Thanks for that clarification. If I have time, I will test this fix.
